### PR TITLE
Add Config flow setup

### PR DESCRIPTION
**Pull request by msp1974**
Angelo,

To help make this acceptable as a native component, I have been working on making a config flow setup.  Couple of things to note:

1) I have tested this pretty well but it wouldn't harm for some more testing.

2) Config flow also works on custom components so we can test without being a native component.

3) When it is a native component it will use zeroconf to find the Wiser Hub on the network and show as a discovered device.  To test this, add an entry to /usr/src/homeassistant/homeassistant/generated/zeroconf.py like below
`"_http._tcp.local.": [
        "wiser"
    ],`

4) In order to upgrade well, if you have an entry in configuration.yaml, it will import it and create a config from it.  You can then delete the entry and it will stay.

5) I have created new battery entities so that it displays the battery level when you go into

> Configuration -> Integrations -> Wiser Heat Hub

> 

I know you were having discussions about battery levels with Drayton.  The min level is currently set at 21 so there are 10 voltage steps from 100% to 0%.  This is defined in const.py and may need to be changed.  Think you said that min voltage for iTRV was about 2.6v?

6) You will notice that when you look at these devices, I have grouped by physical device withe its relevant entities within it (as per the developr docs).  As such, if you look at the wiser hub device, you will see all its sensors and switches and these can be added straight from here to lovelace (nice feature!).

7) And this is one I wasted hours on!  It seems that the list of integrations shown when you click add is cached in the browser and doesn't update betweeen HA restarts (or server restarts).  When you have installed this, either close and reopen browser or do a Shift-F5.  Couldn't work out why it wasn't showing up and spent hours rechecking, googling etc.

Let me know what you think.  There is also a PR for an update to the api.  You need to be able to show a device name and have a unique ID for the config flow to work.

Should also say, not run this through black yet but will do so before merging.

Mark

### CODE REVIEW

**Comment by asantaga** [comment]
Looks good. Im at a conference this week for 3 days (again) but ill review.

**Comment by asantaga** [comment]
testing

**Comment by asantaga** [comment]
Right, Im a bit baffled at this one. 

How do I test this?

**Comment by msp1974** [comment]
There are 3 main tests i think.

1) Have an entry in configuration.yaml and see if it shows up as an integration in the configuration -> integrations section. When clicking on the integration you should see a list of devices with battery levels for all the room stats and itrvs. In each device there should be 1 or more entities. In the wiser hub entity you should see all the sensors and switches relating to the hub. In a room, you should see the climate entries etc.

2) without an entry in configuration.yaml, you should be able to go into configuration -> integrations and be able to add a wiser heat hub, enter the ip and the secret key and it will create all the devices and entities as above.

3) As per the instruction above re zeroconf, delete all entries for the wiser hub (by deleting the integration - from within integration there is a bin in the top right hand corner). Restart HA and you should get a notification that new devices have been discovered. Click the link in this, it should take you through adding the integration but with the IP address pre populated. Enter the secret key and it will set it up as per number 2.

Mark

**Comment by asantaga** [comment]
I tried #2  but when I went to configurations all I had was HACS......

Lets sync up over a zoom call. might be easier

**Comment by msp1974** [comment]
Sorry have no time tonight for a zoom call but maybe later this week if below doesn't help.

Did test 1 work correctly?  Did it show in integrations?  It should work as per 3rd screen shot onward below if so.

For test 2, when in integrations, you should have an add button on the bottom right.  Clicking this will bring up the list of integrations with config flows to be able to add.

image

This will then show the config screen for Wiser Heat Hub.

image

When added, you should see this in integrations.
image

Clicking on it should show you this.
image

And clicking on a device (Wiser Heat Hub in this instance) will give you this.
image

You can then click add to lovelace and it will create the appropriate card with all the entities on.


Also, meant to say in terms of tests:

Test 1 - put some errors in configuration.yaml and ensure handles properly.  Also, delete entry in configuration.yaml after it has created devices and ensure it still loads correctly. If you can also test adding incorrect details etc to ensure error handling works well.

Test 2 - Try adding twice and it should give a clean error that only one entry allowed. Also try entering invalid IP or invalid secret key.  Each case should give a usable error.

Test3 - Once you have configured it, it should not show as discovered again after a reboot.

**Comment by asantaga** [comment]
sorry didnt get to this till now.. Wife wasnt well.. dreaded flu like symptoms.. Shes over it now and all well ...


The component now shows , just worked this time no idea what was different, but when I add the heathub I get the following exception 

```
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 89, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/config/custom_components/wiser/config_flow.py", line 85, in async_step_user
    self._abort_if_unique_id_configured(
TypeError: _abort_if_unique_id_configured() got an unexpected keyword argument 'updates'
2020-03-15 21:56:17 DEBUG (MainThread) [homeassistant.components.ssdp] Scanning
```

Am gonna try upgrading HA.. i might be something like a package version issue

**Comment by asantaga** [comment]
works now..

Looks good.. I wish I knew how all the config flow worked!!

I suppose it time for some RTFM!!!!

Will run it in testing mode for a day or two ...

**Comment by asantaga** [comment]
upgrading all the python libraries in my virtual environment did the trip, my only guess is the issue was with a library.. not the code.

**Comment by asantaga** [comment]
Looks good to me, merged into dev

**Comment by asantaga** [comment]
Docs also updated

**Pull request closed without merging**
