### PR TITLE
Issue #48 - Get, set and copy schedules via HA service

### PR DESCRIPTION
**Pull request by msp1974**
Angelo,

This is certainly beta and may need some more testing and error handling but thought we could get all those that wanted to manage schedules to feedback on this.

This creates 3 services - wiser.get_schedule, wiser.set_schedule and wiser.copy_schedule.

Get_schedule - reads the room schedule and writes to the filename specified in yaml format.  This is however in wiser format ie times not in time format and temps in x10 format.  It is really so that you can download the current schedule and create the file to be able to amend or copy etc to other schedules.

Set_schedule - this reads the file specified and writes to the entity selected

Copy_schedule - the allows you to specify a from and to entity and it copies the schedule between them (this is something that the wiser app cannot do and is a real pain when setting up many rooms!)

In my mind, these services will allow someone to create multiple schedules for a room (one file for each) and be able to use automation to set the correct schedule as needed.

Let me know what you think.
KR
Mark

PS Obviously needs the updates to the API in my other PR.

### CODE REVIEW

**Comment by msp1974** [comment]
Angelo,

Have been continuing to work on this and trying to get it to allow you to be able to use proper times and temps in the scehdule file.  Will finish today but didn't want you to merge until I have sent you this so you are not doing twice.

KR Mark

**Comment by msp1974** [comment]
Ok, I have been testing and it all now seems to work well.  Im ready for you to review when you've got time.

KR Mark

**Comment by asantaga** [comment]
Just reviewing it , looks good, testing now

**Comment by asantaga** [comment]
getting an error when executing "get_schedule"

```
2020-01-19 20:27:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140207696535120] Could not read schedule data for room 3
Traceback (most recent call last):
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1262, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/config/custom_components/wiser/climate.py", line 148, in get_schedule
    scheduleData = handler.get_room_schedule(target_device.roomId)
  File "/home/asantaga/src/ha_dev/venv_wiser/homeassistant/config/custom_components/wiser/__init__.py", line 218, in get_room_schedule
    raise Exception("Could not read schedule data for room {}".format(room_id))
Exception: Could not read schedule data for room 3

```

Debugging

**Comment by asantaga** [comment]
ok, 
If you query the room once, it works fine, but if you query the room twice it then gives the error.. still debugging the code, the bug is in wiserHub

**Comment by asantaga** [comment]
ok, this is a little weird. 

if you query the room once, then it works, but if you query the room "twice" then you get an error.
Dont understand why.... very weird.. I so wish I could step-by-step debug HA...

Does this bug occur in your instance too?

**Comment by msp1974** [comment]
Yes it is occurring.  However, if you query another room straight away it works fine.  Very strange.  Will also try and debug what is going on.

**Comment by msp1974** [comment]
Angelo,  I cannot find what is causing this.

If I run the api standalone and call the function twice in rapid succession, all fine.
If I get the api to raise an exception and pass schedule data when running under HA, logs the exception in HA with full schedule data.
If I then put a debug log on the schedule data in the variable it is returned to from the api call, the second time (and more unless I wait 20 secs or so), it shows an empty variable.

Not sure where to go from here!

**Comment by asantaga** [comment]
Same here, i also ran the test from the api and all was ok.... im gonna carve out some time tomorrow and dig into it...

Im wondering if a forced refresh, whilst rather blunt, will solve it....

Till tomorrow

**Comment by msp1974** [comment]
If this works and you're ok to do that would be great.  Having a read through the docs, this maybe that we need to change this custom component to use the event loop.  Was reading this and it maybe our issue. [https://developers.home-assistant.io/docs/en/asyncio_index.html](url)

**Comment by msp1974** [comment]
BTW, I now have an automation that can set the schedules based on whether the house is occupied or not.  It's very cool! ;-)  And weirdly, this issue does not show when setting them.

**Comment by msp1974** [comment]
Angelo,

Hope you're well.  I have been continuing to investigate this issue by doing the following things:
1) rewrite the component to use asyncs - issue persists
2) investigate if there is a pointer issue as we were not iterating over the whole dict - issue persists
3) moving the whole function into the service method and removing the method from _init_.py - issue persists.
4) doing a refresh if nothing returned and calling again (as you suggested) - works!

Fundamental seems to be that if calling the api directly (ie not through HA) it works fine.  So I think I agree with you that this must be some sort of threading issue, although rewriting this all with asyncs should have removed that as it now all runs on the main thread instead of syncthreads.  So, possibly some HA quirk that I cannot debug that the api call itself is on another thread that is creating another instance of the api (although that should also perform a refresh when created).  I will update with a check and refresh of nothing returned and update this PR this week.

Also, as I have moved everything to asyncs, will send you this as a PR later on (when tested fully) as this is more HA compliant now.

**Comment by asantaga** [comment]
Hey thanks, sorry you went through the whole hassle of rewriting everything as async calls.

Disclaimer : Ive never played with the async mode so this is going to be great for me as I can learn from it!!

Let me know when ready to test.

**Comment by asantaga** [comment]
will be closed in preference to PR#54.

Leaving open for the time being

**Comment by asantaga** [comment]
Closing this PR as all the updates are in PR54. If we need it later we can open it up again

**Comment by agitate** [comment]
Sorry to wake this issue from the dead, but I'm having what looks like a similar issue. I've got a couple of buttons on my HA to load up different schedules (normal, all day, etc.). If I run them once, using set_schedule, it works fine, and if I don't do it again for a while, it continues to work fine. However, during testing I would randomly get:

`2021-01-29 15:41:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/wiser/__init__.py", line 505, in set_schedule
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 564, in setSchedule
    raise WiserNotFound("No schedule found that matches id")
wiserHeatingAPI.wiserHub.WiserNotFound: No schedule found that matches id`

I was tail-ing the logs when I was testing it, and it seems like if I run the set_schedule and then wait for this to show up in the logs:

`2021-01-29 15:41:08 INFO (SyncWorker_6) [wiserHeatingAPI.wiserHub] Updating Wiser Hub Data
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] **Wiser Hub data updated**
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 1, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 2, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 3, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 4, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 5, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 6, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 7, state=Auto
2021-01-29 15:41:08 INFO (MainThread) [custom_components.wiser.const] State requested for room 8, state=Auto`

and then run set_schedule again, it would work okay. Weird. So I was wondering, is there some way I can trigger that wiser update manually, after each call to set_schedule?

(Love this integration by the way. Awesome work! Coding all of the schedule stuff myself was amazing and let me fill in the many many gaps in the default Wiser app. So Thank you!)

**Comment by agitate** [comment]
Actually, scrap that. I have a job that runs every morning at 05:00 which resets the heating to the "normal" schedule (to remove any all day override schedules that might have been set). That failed last night, without any other set_schedule calls being run any time near then, so it looks like a totally separate issue from this one. I'll post it up as a new issue. Here is the output from the attempt to set_schedule last night:

`2021-01-30 05:00:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/wiser/__init__.py", line 505, in set_schedule
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 564, in setSchedule
    raise WiserNotFound("No schedule found that matches id")
wiserHeatingAPI.wiserHub.WiserNotFound: No schedule found that matches id`

**Pull request closed without merging**
