### PR TITLE
Rewritten to use asyncs

### PR DESCRIPTION
**Pull request by msp1974**
Angelo,

As discussed, here is the component updated to use asyncs.  Points to note:

1) Also added some additional switches to set ecomode, comfort mode plus more (requires update to api which I will send you PR)
2) wiser.get_schedule service erroring on second call is now fixed
3) I have created a constant file and a utilities file to tidy this up a bit

Most of this work has been done by looking at other components that use asyncs but having tested it as best I can, seems very stable.

Mark

### CODE REVIEW

**Comment by asantaga** [comment]
Nice, thanks. 

I'll try and review and merge tomorrow.  Does this PR replace #49 ???

**Comment by msp1974** [comment]
Yes it does but left seperate in case needed longer review time.

**Comment by asantaga** [comment]
Testing and seams to work flawlessly.. Im running it overnight before merging ..

Cant see any fault with it.

Also many thanks for the code updates, you've really morphed the code nicely!!! Almost dont recognise it.. :-)

**Comment by asantaga** [comment]
Merged it branch R1.9DEV

I have a few other things I want to merge into this branch

**Comment by asantaga** [comment]
This is now merged into R1.9Dev.

**Pull request closed without merging**
