### PR TITLE
Lgo44 hub v2 2024 07 updated 2024 09

### PR DESCRIPTION
**Pull request by LGO44**
add new features available with wiser Hub V2

### CODE REVIEW

**Comment by LGO44** [comment]
notes about the new features provided by the PR478 and 486
[PR486.pdf](https://github.com/user-attachments/files/16147837/PR486.pdf)
the new features provided by the PR

**Comment by LGO44** [comment]
@msp1974  here are the last enhancement in my PR.
I have an issue in aioWiserHeatAIP wher I want to create WidowDoorsensor, If you have an idea it will be nice

I have created a binary_sensor.py file directly derived from your switch.py because it's very easy to add binary_sensors.

I hope that it's clear enough, if not feel free ta ask some more informations.

[Wiser hub V2 2024 09.pdf](https://github.com/user-attachments/files/16948835/Wiser.hub.V2.2024.09.pdf)

[config_entry-wiser-04b54a69ee02ea23d613b96cb315965b (5).json](https://github.com/user-attachments/files/16948834/config_entry-wiser-04b54a69ee02ea23d613b96cb315965b.5.json)

[config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json](https://github.com/user-attachments/files/16948811/config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json)

**Comment by msp1974** [comment]
This is great.  I see it has some conflicts with current code, so let me look at this over the next week or so.  Can you tell me more about your issue with windowdoor sensors.  Is it because they dont seem to have a device type entry like all other devices?

**Comment by LGO44** [comment]
> This is great. I see it has some conflicts with current code, so let me look at this over the next week or so. Can you tell me more about your issue with windowdoor sensors. Is it because they dont seem to have a device type entry like all other devices?
> 
> Edit: oh, sorry see that they are binarysensor in the config as device type. Tell me more your issue.

Thanks a lot to spend time to look at my code.

The issue on windowdoorsensor happen when I want to create these device by calling the code by  "WindowDoorSensor": {..
or BinarySensor{..
the Wiser platform cannot be initialized an error in the coordinator.py is raised...

devices.py
    "WindowDoor": {
        "class": _WiserWindowDoor,
        "collection": _WiserWindowDoorCollection,
        "endpoint": WISERWINDOWDOOR,
        "device_id_field": "DeviceId",
    },
    "BinarySensor": {
        "class": _WiserBinarySensor,
        "collection": _WiserBinarySensorCollection,
        "endpoint": WISERBINARYSENSOR,
        "device_id_field": "DeviceId",
    },

**Comment by msp1974** [comment]
Yes, been having a look and see the issue.  Think I have it resolved but need to do some more testing.

Basic issue is that I think you are looking at it as a DoorWindow sensor and not a BinarySensor of type windowdoor.  Think it needs to be like how we have OnOffLights and DimmableLights, ie they are both Lights but with different types.

I'll push this into the repo when happy with it and you can then try it out.

**Comment by LGO44** [comment]
@msp1974 Thanks for your help! I think I was temporally blind (paralympics games in Paris maybe).
Once more you win!

I have tested the dev branch of the aioWiserHeatAPI, I got immediately a windowdoorsensor
image

I adjust the attributes:

image

I will push the modifications in a PR

**Comment by msp1974** [comment]
Hi Christian,  so I have worked my way through this PR and added most of it to the current dev branch.  Things not added yet/won't be added.

1. I have not added the equipment sensors.  I agree they need to be there but need more time to work through this.
2. I have not added attributes to sensors where this information already exists on other entities.
3. I have not added your fix for issue 461 because I think that is not the fix for this issue.  Only deals with 1 entity and not the others.  I will look into this with more time.

I intend to release the dev version tomorrow as it has some fixes in it people have been waiting for but also wanted to get some progress on this PR as you have also been waiting some time.

If you agree, I will then close this PR, but open issues for the outstanding pieces - eg Equipment sensors and you can log any issues you find in this next update.

**Comment by LGO44** [comment]
@msp1974 Hi Mark, thank you to take in account this PR
This PR is a proposition and of course all your remarks are welcome.
I agree that you close this PR.
I'm working on the capability off the hub to configure notification that can be enabled or not 

-          window or door
-         over or under power notification for smartplugs and PTE

What should be the best way to work , create a new PR or create issue on the GitHub or anything else, it's just to find the best way for efficiency and ease of use?

The point 1 for me is a major enhancement of the Wiser offer.
The point 2 , feel free for that. Sometime I duplicate attributes because it seems to me that it precise the sensor.
The point 3 for issue 461 is a way I find to identify surely all the data coming from my 3 hub one V1 and 2 V2

 I don't know if you heard that Schneider want to bring IA in home management, so Wiser will keep on growing...


> Hi Christian, so I have worked my way through this PR and added most of it to the current dev branch. Things not added yet/won't be added.
> 
> 1. I have not added the equipment sensors.  I agree they need to be there but need more time to work through this.
> 2. I have not added attributes to sensors where this information already exists on other entities.
> 3. I have not added your fix for issue 461 because I think that is not the fix for this issue.  Only deals with 1 entity and not the others.  I will look into this with more time.
> 
> I intend to release the dev version tomorrow as it has some fixes in it people have been waiting for but also wanted to get some progress on this PR as you have also been waiting some time.
> 
> If you agree, I will then close this PR, but open issues for the outstanding pieces - eg Equipment sensors and you can log any issues you find in this next update.

**Pull request closed without merging**
