### PR TITLE
Devhubv2lgo

### PR DESCRIPTION
**Pull request by LGO44**
This is the branch I use to my tests.

Questions:

1. The switch "switch.wiser_shutter_salle_salon_jardin_respect_summer_comfort" has been created, it's state isn't updated...

exemple:
I turn_on the switch, it update in the Hub but the switch states return to off after a few seconds ....
logs:
_**2023-11-16 14:37:37.226 DEBUG (MainThread) [aioWiserHeatAPI] Sending command to url: http://{}:{}/data/v2/domain/Shutter/1 with parameters {'RespectSummerComfort': 'true'}
2023-11-16 14:37:37.285 DEBUG (MainThread) [aioWiserHeatAPI] Wiser shutter- set_respect_summer_comfort command successful**
2023-11-16 14:37:37.488 INFO (MainThread) [custom_components.wiser.coordinator] Hub update completed for WiserHeat045FDD
**2023-11-16 14:37:38.679 DEBUG (MainThread) [aioWiserHeatAPI] Sending command to url: http://{}:{}/data/v2/domain/Shutter/1 with parameters {'RespectSummerComfort': 'false'}
2023-11-16 14:37:38.811 DEBUG (MainThread) [aioWiserHeatAPI] Wiser shutter- set_respect_summer_comfort command successful**
_

2. In number.py I cannot fixed an issue on the 
Add lift, tilt position for any shutter summer comfort position
    for shutter in data.wiserhub.devices.shutters.all:
               
        wiser_numbers.extend(
            [
                #WiserSummerComfortLiftNumber(data,shutter,"summer_comfort_lift"),
                #WiserSummerComfortTiltNumber(shutter,  "summer_comfort_tilt")
            ],
        )

### CODE REVIEW

**Comment by msp1974** [comment]
1.  I have seen this (mainly on plugs) where the integration updates after setting a switch too quicky and the state is not yet updated on the hub.  For testing, add a delay parameter to force_hub_update request.  Ie self.force_hub_update(1) and see if that works.
2. What is the issue?

**Comment by LGO44** [comment]
Point 1 : 
> 1. I have seen this (mainly on plugs) where the integration updates after setting a switch too quicky and the state is not yet updated on the hub.  For testing, add a delay parameter to force_hub_update request.  Ie self.force_hub_update(1) and see if that works.

I have put  "self.force_hub_update(1) ", "self.force_hub_update(5) " ,"self.force_hub_update(20)" no result.

My test:
  Initial :  on the wiser home application  the shutter doesn't "Respect_summer_comfort"

**Comment by LGO44** [comment]
> 2 What is the issue?

I tried to create a class WiserSummerComfortLiftNumber(CoordinatorEntity, NumberEntity):
 but I can't configure the definition either based on **class WiserFloorTempSensorNumber** or **class WiserDiscomfortOutdoorTempNumber(CoordinatorEntity, NumberEntity):**

i'm a bit lost

**Comment by msp1974** [comment]
Ok.  For issue 1.

You have this in switch.py for WiserShutterSummerComfortSwitch.
```
self._is_on = True if self._shutter.respect_summer_comfort == "off" else False
```
However aiowiserheat api returns True or False for respect_summer_comfort not on/off.  Not sure whether api is wrong or the line above but they need to match value types.

**Comment by LGO44** [comment]
> Ok. For issue 1.
> 
> You have this in switch.py for WiserShutterSummerComfortSwitch.
> 
> ```
> self._is_on = True if self._shutter.respect_summer_comfort == "off" else False
> ```
> 
> However aiowiserheat api returns True or False for respect_summer_comfort not on/off. Not sure whether api is wrong or the line above but they need to match value types.
@msp1974 Thanks a lot.
FIXED! You are right.
I think I could have stayed in front of the code for years without finding the cause of the issue

**Comment by LGO44** [comment]
@msp1974 As I'm a beginner on github I've also mase a pull request on my repository https://github.com/LGO44/aioWiserHeatAPI/pull/1 .
I don't know how can I upload it in your repository.

**Comment by msp1974** [comment]
Replaced by #427

**Pull request closed without merging**
