### PR TITLE
Display presets and support boost

### PR DESCRIPTION
**Pull request by msp1974**
Added presets to show more than just auto or heat/cool.  Will now show if boosted, override on auto, away mode etc.

Also can either select boost from presets or use set preset service call.

Currently uses boost_temp and boost_time from configuration.yaml as didn't want to break this.  Improvements that could be made to this:
1) Would be to use a delta temp instead of fixed boost temp.
2) Ability to boost for different time periods.  Couldn't think of a way to do this other than a custom service as using different presets (Boost30, Boost60 etc) would not work (I think) if the boost was not set on HA.

Mark

### CODE REVIEW

**Comment by asantaga** [comment]
thanks, will review tonight. , also fixed some bugs in setting temperature ( mix of using 10 and 100 for C)..

Im doing some testing (SHOCK HORROR) before making it a new release on HACS. Feel free to pull the latest trunk code , and upgrade pypi package wiser-heating-api.

thanks again, good to collaborate!

**Comment by msp1974** [comment]
I have updated this PR some more (based on the feedback seen on the issues re boost).

Added: You can now set the boost time using presets (i know I said it wouldn't work!).
Updated: The boost temp is now a delta and is added to the current temp.  Delta is set in configuration.yaml as boost_temp.  This is obviously a breaking change as if set to a value for previous functionality it will error on the hub as above 30C.
Added: With updated api supporting Off mode setting, now HA can set to off.

I hope you like this.  No offence taken if you don't want to merge, or want to take some of the ideas and not all etc.

With this functionality, it works really nice now in HA to be able to completely control the wiser TRVs (except set schedule).

Mark

**Comment by asantaga** [comment]
And why wouldnt I want to merge? 

:-)

**Comment by asantaga** [comment]
Very nice, I updated the readme and added a new image..

**Pull request merged**
