### PR TITLE
get/set/copy schedules for rooms/hotwater/smartplugs

### PR DESCRIPTION
**Pull request by msp1974**

### CODE REVIEW

**Comment by lwis** [comment]
@msp1974 Forgive my confusion, but which entity id should I use for hot water schedules?

**Comment by msp1974** [comment]
@lwis if you're using the dev branch then use the wiser hot water sensor. If you are using from HACs then you will need to wait until this functionality is published.  Angelo updated the wiser heating api on pypi over the weekend ... which is needed for the dev branch to function.

I should get to releasing this this week.  Need to do some more testing and update the documentation.

KR
Mark

**Comment by lwis** [comment]
@msp1974 thanks, I just tried to test it and got;

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/wiser/sensor.py", line 442, in async_update
    self.data.schedules[str(self.entity_id)] = self.data.wiserhub.getHotwater().get("ScheduleID")
AttributeError: 'list' object has no attribute 'get'
```

**Comment by msp1974** [comment]
@lwis you will see update was published to HACs yesterday. Could you try for me and see how you get on.

**Comment by lwis** [comment]
@msp1974 thanks, seems to be working fine for me.

**Pull request merged**
