### PR TITLE
Used black to reformat Python code

### PR DESCRIPTION
**Pull request by michthom**
Python files automatically reformatted (using black 19.10b0)

### CODE REVIEW

**Comment by asantaga** [comment]
Will review and test asap

**Comment by asantaga** [comment]
tested all ok and looks good..

I'll run it through a pep analyzer later this week. I did it for the lightwaverf component I built but never got around to publishing that either

**Comment by michthom** [comment]
> I'll run it through a pep analyzer later this week. 

I'm not sure you need to, given the comment in the [development checklist](https://developers.home-assistant.io/docs/en/development_checklist.html) and the [linked post](https://developers.home-assistant.io/blog/2019/07/31/black.html)?:

> As part of adopting Black, all style checks in flake8 and pylint have been disabled.

Black's [purpose in life](https://black.readthedocs.io/en/stable/) is to take the burden of formatting off your to-do list - permanently! It's the first time I've used it, but I'm a big fan already.

**Comment by asantaga** [comment]
Oh , the checklist is new..  I'll review it but yeah I think your right, might be a lot easier now than it was before...

**Pull request merged**
