### PR TITLE
Added boost option for setpoint heating.

### PR DESCRIPTION
**Pull request by charlesomer**
My attempt at adding functionality from #148.

This seems to work but might need tidying up, let me know what you think!

### CODE REVIEW

**Comment by asantaga** [comment]
Checking it out

**Comment by asantaga** [comment]
Im being thick here (been a while) , but what config options would this give the user?


Code looks ok I just want to note what needs to be added to the readme.md

**Comment by charlesomer** [comment]
Basically it just means that when a user adjusts the temperature via the UI (or in turn via HomeKit), instead of it changing the temperature until the next scheduled set point, it "boosts" to that temperature for the default boost time :)

**Comment by asantaga** [comment]
hum, sorry I haven't come back to you on this, but this behaviour would be different to what the app provides right?

@msp1974  , what do you think? 

What we could do is make this a switch so the user could decide on the behabour?

**Comment by charlesomer** [comment]
No worries :) Yes this behaviour is slightly different to the Wiser app

It’s current an option that can be changed in the integrations settings via the UI (I think I’ve implemented it correctly).

**Comment by asantaga** [comment]
OK, I'll try it out on my dev environment.. Not much need for heating nowadays! :-)

**Review by asantaga — COMMENTED** [review]
Looks good, I was a bit delayed in testing this.

**Comment by asantaga** [comment]
Need to add to docs then will merge into master.

**Comment by asantaga** [comment]
Added docs to readme.md and merged into dev branch. Also released new beta. If no one reports issues I'll merge to master early next week and release 2.6 from beta

**Comment by asantaga** [comment]
thank you :-)

**Comment by charlesomer** [comment]
No problem 😄 Thank you for looking into this. I've tried to test the latest beta but it looks like these changes aren't there :/

**Comment by asantaga** [comment]
fixed, when I created the release I based it on master and not dev  (2.6Beta3 now)}

My fault for doing it quickly in between other work stuff

**Pull request closed without merging**
