### PR TITLE
Lgo44 on off lights

### PR DESCRIPTION
**Pull request by LGO44**
add new wiser device OnOffLight

### CODE REVIEW

**Comment by msp1974** [comment]
I would like to get the code we already have in progress working before we add more to it.  Do you have on/off lights to test?  Do they work with the API as they are as don't recall if they are currently included.

Anyway, can we focus on what is currently in the lgo44 repo, know this all works, so that we can release it and then we can progress this PR.

Thanks

**Comment by LGO44** [comment]
Effectively I have an OnOffLight, I tested it and everything is right.
In the wiser platform, in the light.py I' ve created a OnOffLight class  
image

I have put some screen shot in the doc folder 

In the **wiserHeatAPIv2** I modified the devices.py 
**elif device.get("ProductType") in ["DimmableLight", "OnOffLight"]:**
I created a PR in the API, here is the domain json file got by the hub discovery service.
[domain-20220324-111550.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8346150/domain-20220324-
111550.zip)

**Comment by msp1974** [comment]
This seems to have many changes in it that I think are not related to this PR.  Think this is because you are submitting as we are still working on the other things.  If we can finish off the dimable ligths and shutters, make sure we are fully happy with that, then we can modify the wiserHeatAPIv2 to do the onoff light correctly and then add this change in.

**Comment by msp1974** [comment]
This is in current lgo44 branch and dev branch

**Pull request closed without merging**
